[package]
name = "myo"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
spin = "0.5.2"
volatile = "0.2.6" # TODO: Figure out how to use latest (0.4.4)

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]